var PATH={
    index:{
        knowledge:"/knowledge"
    },
    equipment:{
        detail:"/student/detail/",
        dynamics:"/student/studyDynamics",
        errorLib:"/student/errorLib",
        interactQuestion:"/student/interactQuestion",
        onlineQuestion:"/student/onlineQuestion",
        correctPaper:"/student/correctPaper",
        content:"/equip/content",
        entranceResult:"/student/entranceResult",
        entranceReport:"/student/entranceReport",
        entryQuestions:"/student/entryQuestions"
    },
    user:{
        set:"/person/set",
        admin:"/user/Content",
        other:"/user/otherContent"
    }
};
module.exports=PATH;